---
- hosts: 52.5.252.107
  remote_user: admin
  tasks:

# EC2 extra volume
  - name: extra volume has a filesystem
    become: true
    filesystem:
      force: no
      fstype: ext4
      dev: /dev/xvdb

  - name: mountpoint has correct permissions
    become: true
    file:
      path: /mnt/large
      owner: admin
      state: directory

  - name: extra volume is mounted
    become: true
    mount:
      name: /mnt/large
      src: /dev/xvdb
      fstype: ext4
      state: mounted

# debian packages  
  - name: required debian packages are present
    apt: pkg={{ item }} state=present
    become: true
    with_items:
      - emacs24-nox
      - debian-goodies
      - git

  - name: unwanted debian packages are absent
    apt: pkg=python3-twisted state=absent
    become: true

# python packages
  - name: python v3.x packages (PIP) are present
    become: true
    pip:
      requirements: /home/admin/my_stratum/ansible/requirements.txt
      executable: pip3

# sources
  - name: custom stratum server at latest version
    git: repo=https://github.com/cbouilla/3sum-pool.git
         dest=/home/admin/my_stratum
    notify:
      - restart stratum server
  
# systemd config
  - name: systemd service file is present
    become: true
    copy: 
      src: stratum.service 
      dest: /etc/systemd/system/
    notify:
      - reload systemd
      - restart stratum server

  - name: stratum server is running
    become: true
    systemd:
      name: stratum
      daemon_reload: yes
      state: started
      enabled: yes


  handlers:
  - name: restart stratum server
    become: true
    systemd:
      name: stratum
      state: restarted

  - name: reload systemd
    become: true
    systemd:
      daemon_reload: yes

  
